const fontWeight = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
};

export const typography = {
  display1: {
    fontSize: "40px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  display2: {
    fontSize: "36px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading1: {
    fontSize: "32px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading2: {
    fontSize: "28px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading3: {
    fontSize: "25px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading4: {
    fontSize: "22px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading5: {
    fontSize: "20px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading6: {
    fontSize: "18px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  large: {
    fontSize: "16px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  base: {
    fontSize: "14px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  small: {
    fontSize: "12px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  XSmall: {
    fontSize: "11px",
    textDecoration: "none",
    fontFamily: "DM Sans",
    fontWeight: {
      ...fontWeight,
    },
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "0.04em",
    lineHeight: "48px",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
};
